version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errcheck
    - errorlint
    - exhaustive
    - gosec
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nilnil
    - noctx
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - wrapcheck
