included:
  - host/Package.swift
  - host/Sources
  - host/Tests

excluded:
  - host/.build
  - build

only_rules:
  - for_where
  - function_body_length
  - identifier_name
  - line_length
  - statement_position
  - unused_optional_binding

line_length:
  warning: 120
  error: 120
