import Foundation
@preconcurrency import Virtualization

/// Immutable capabilities manifest loaded from the nix-darwin closure.
///
/// Maps action names to handler scripts in /nix/store/. The manifest is
/// generated by `dvm.capabilities` in guest-plumbing.nix and passed to
/// dvm-core via `--capabilities <path>`.
struct CapabilitiesManifest: Sendable {
    /// action name → absolute /nix/store/ handler path
    let handlers: [String: String]

    /// Load and validate a capabilities manifest from a JSON file.
    /// The file itself must be in /nix/store/ and all handler paths must be too.
    static func load(from path: String) throws -> CapabilitiesManifest {
        guard path.hasPrefix("/nix/store/") else {
            throw HostActionError.manifestNotInStore(path)
        }

        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        guard let dict = try JSONSerialization.jsonObject(with: data) as? [String: String] else {
            throw HostActionError.invalidManifest("expected JSON object with string values")
        }

        // Validate all handler paths
        for (name, handlerPath) in dict {
            guard handlerPath.hasPrefix("/nix/store/") else {
                throw HostActionError.handlerNotInStore(name: name, path: handlerPath)
            }
            guard FileManager.default.isExecutableFile(atPath: handlerPath) else {
                throw HostActionError.handlerNotExecutable(name: name, path: handlerPath)
            }
        }

        return CapabilitiesManifest(handlers: dict)
    }
}

enum HostActionError: Error, CustomStringConvertible {
    case manifestNotInStore(String)
    case invalidManifest(String)
    case handlerNotInStore(name: String, path: String)
    case handlerNotExecutable(name: String, path: String)
    case unknownAction(String)
    case payloadTooLarge(Int)
    case malformedRequest(String)

    var description: String {
        switch self {
        case .manifestNotInStore(let p):
            return "capabilities manifest must be in /nix/store/: \(p)"
        case .invalidManifest(let msg):
            return "invalid capabilities manifest: \(msg)"
        case .handlerNotInStore(let name, let path):
            return "handler for '\(name)' must be in /nix/store/: \(path)"
        case .handlerNotExecutable(let name, let path):
            return "handler for '\(name)' is not executable: \(path)"
        case .unknownAction(let name):
            return "unknown action: \(name)"
        case .payloadTooLarge(let size):
            return "payload too large: \(size) bytes (max 65536)"
        case .malformedRequest(let msg):
            return "malformed request: \(msg)"
        }
    }
}

/// Listens on a vsock port for guest host-action requests.
///
/// When a guest process (dvm-host-cmd) connects, it sends:
///   action_name\n
///   payload bytes...
///   (shuts down write end to signal EOF)
///
/// The bridge looks up the action in the immutable capabilities manifest,
/// spawns the handler at its absolute /nix/store/ path with a scrubbed
/// environment, pipes the payload to stdin, and returns the exit code.
///
/// Security model:
/// - The manifest is immutable — generated by nix-darwin and loaded from /nix/store/.
///   No mutable config files, no runtime modification.
/// - Handlers are absolute /nix/store/ paths — no PATH resolution, no env injection.
/// - Environment is scrubbed to PATH=/usr/bin:/bin only.
/// - 64KB payload cap, 10s execution timeout.
/// - Vsock has no caller authentication — any guest process can connect.
///
/// Protocol:
///   Request:  action_name\npayload   (guest shuts down write after sending)
///   Response: 0\n                     (exit code, or code\x00error\n on failure)
@MainActor
final class HostCommandBridge {
    static let defaultPort: UInt32 = 6176

    let socketDevice: VZVirtioSocketDevice
    let listenPort: UInt32
    /// Current manifest. Access is serialized through the bridge's nonisolated
    /// methods running on the utility dispatch queue — reads are non-overlapping.
    /// Writes happen only from the main actor (reload), so no data race.
    nonisolated(unsafe) private var manifest: CapabilitiesManifest

    private var listenerDelegate: ListenerDelegate?

    init(
        vm: VZVirtualMachine,
        manifest: CapabilitiesManifest,
        listenPort: UInt32 = defaultPort
    ) throws {
        guard let device = vm.socketDevices.first as? VZVirtioSocketDevice else {
            throw BridgeError.noSocketDevice
        }
        self.socketDevice = device
        self.listenPort = listenPort
        self.manifest = manifest
    }

    /// Hot-reload the capabilities manifest from a new closure.
    func reload(from path: String) throws {
        let newManifest = try CapabilitiesManifest.load(from: path)
        self.manifest = newManifest
        DVMLog.log("host action bridge reloaded (actions: \(newManifest.handlers.keys.sorted().joined(separator: ", ")))")
    }

    func start() {
        let listener = VZVirtioSocketListener()
        let delegate = ListenerDelegate(bridge: self)
        self.listenerDelegate = delegate
        listener.delegate = delegate
        socketDevice.setSocketListener(listener, forPort: listenPort)
        DVMLog.log("host action bridge listening on vsock port \(listenPort) (actions: \(manifest.handlers.keys.sorted().joined(separator: ", ")))")
    }

    /// Handle a guest connection. Runs on a background thread.
    /// The connection object must stay alive for the duration.
    nonisolated func handleConnection(_ connection: VZVirtioSocketConnection) {
        let fd = connection.fileDescriptor

        // Read request until EOF or 64KB + header limit
        let maxBytes = 65536 + 1024  // payload cap + room for action name line
        var data = Data()
        let buf = UnsafeMutableRawPointer.allocate(byteCount: 4096, alignment: 1)
        defer { buf.deallocate() }

        while data.count < maxBytes {
            let n = read(fd, buf, min(4096, maxBytes - data.count))
            if n <= 0 { break }
            data.append(buf.assumingMemoryBound(to: UInt8.self), count: n)
        }

        guard !data.isEmpty else {
            writeResponse(fd: fd, code: 1, error: "empty request")
            return
        }

        guard let request = String(data: data, encoding: .utf8) else {
            writeResponse(fd: fd, code: 1, error: "invalid UTF-8")
            return
        }

        // Parse: first line = action name, rest = payload
        guard let newlineIndex = request.firstIndex(of: "\n") else {
            writeResponse(fd: fd, code: 1, error: "malformed request: no newline separator")
            return
        }

        let actionName = String(request[request.startIndex..<newlineIndex])
        guard !actionName.isEmpty else {
            writeResponse(fd: fd, code: 1, error: "empty action name")
            return
        }

        let payload = String(request[request.index(after: newlineIndex)...])
        let payloadBytes = payload.utf8.count
        if payloadBytes > 65536 {
            writeResponse(fd: fd, code: 1, error: "payload too large: \(payloadBytes) bytes (max 65536)")
            return
        }

        // Look up handler in manifest
        guard let handlerPath = manifest.handlers[actionName] else {
            DVMLog.log(level: "warn", "unknown action: \(actionName)")
            writeResponse(fd: fd, code: 1, error: "unknown action: \(actionName)")
            return
        }

        DVMLog.log(level: "debug", "host action: \(actionName) (payload: \(payloadBytes) bytes)")

        executeHandler(fd: fd, handlerPath: handlerPath, actionName: actionName, payload: payload)
    }

    private nonisolated func executeHandler(fd: Int32, handlerPath: String, actionName: String, payload: String) {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: handlerPath)
        process.arguments = []
        process.currentDirectoryURL = URL(fileURLWithPath: "/")
        process.environment = ["PATH": "/usr/bin:/bin"]

        // Pipe payload to stdin
        let stdinPipe = Pipe()
        process.standardInput = stdinPipe

        // Capture stderr for error reporting
        let stderrPipe = Pipe()
        process.standardError = stderrPipe

        // 10s timeout
        let timeoutItem = DispatchWorkItem { [weak process] in
            process?.terminate()
        }
        DispatchQueue.global().asyncAfter(deadline: .now() + 10, execute: timeoutItem)

        do {
            try process.run()

            // Write payload to stdin then close
            if !payload.isEmpty {
                stdinPipe.fileHandleForWriting.write(payload.data(using: .utf8)!)
            }
            stdinPipe.fileHandleForWriting.closeFile()

            process.waitUntilExit()
            timeoutItem.cancel()

            let exitCode = process.terminationStatus
            if exitCode != 0 {
                let stderrData = stderrPipe.fileHandleForReading.readDataToEndOfFile()
                let stderrStr = String(data: stderrData, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
                if !stderrStr.isEmpty {
                    writeResponse(fd: fd, code: exitCode, error: stderrStr)
                } else {
                    writeResponse(fd: fd, code: exitCode, error: nil)
                }
            } else {
                writeResponse(fd: fd, code: 0, error: nil)
            }
        } catch {
            timeoutItem.cancel()
            DVMLog.log(level: "error", "host action '\(actionName)' exec failed: \(error)")
            writeResponse(fd: fd, code: 1, error: "exec failed: \(error)")
        }
    }

    private nonisolated func writeResponse(fd: Int32, code: Int32, error: String?) {
        let response: String
        if let error, !error.isEmpty {
            response = "\(code)\0\(error)\n"
        } else {
            response = "\(code)\n"
        }
        let bytes = Array(response.utf8)
        _ = bytes.withUnsafeBufferPointer { ptr in
            write(fd, ptr.baseAddress!, ptr.count)
        }
    }
}

// MARK: - VZVirtioSocketListenerDelegate

extension HostCommandBridge {
    final class ListenerDelegate: NSObject, VZVirtioSocketListenerDelegate, @unchecked Sendable {
        let bridge: HostCommandBridge

        init(bridge: HostCommandBridge) {
            self.bridge = bridge
        }

        nonisolated func listener(
            _ listener: VZVirtioSocketListener,
            shouldAcceptNewConnection connection: VZVirtioSocketConnection,
            from socketDevice: VZVirtioSocketDevice
        ) -> Bool {
            nonisolated(unsafe) let conn = connection
            DispatchQueue.global(qos: .utility).async {
                self.bridge.handleConnection(conn)
            }
            return true
        }
    }
}
